-- AUTOGENERADO por src/db/generate-postgres-ddl.js — NO EDITAR A MANO.
-- Fuente: information_schema.columns de data/warehouse/eyg_nexus.duckdb (introspección en vivo).
-- Para regenerar: npm run db:pg:ddl
-- Ver docs/TECH_DEBT_UNREPRODUCIBLE_TABLES.md para las tablas sin script generador propio.

CREATE TABLE IF NOT EXISTS marts."equipment_part_lifecycle_events" (
  "lifecycle_event_id" TEXT,
  "fieldbeat_task_id" BIGINT,
  "event_date" TIMESTAMPTZ,
  "client_key" TEXT,
  "client_name" TEXT,
  "equipment_internal_id" TEXT,
  "equipment_uuid" TEXT,
  "task_type" TEXT,
  "task_state" TEXT,
  "technician_names" TEXT,
  "linked_zendesk_ticket_id" TEXT,
  "used_part_id" TEXT,
  "raw_part_identifier" TEXT,
  "part_name" TEXT,
  "quantity" BIGINT,
  "dolibarr_product_id" BIGINT,
  "dolibarr_ref" TEXT,
  "dolibarr_label" TEXT,
  "match_status" TEXT,
  "match_method" TEXT,
  "match_confidence" DOUBLE PRECISION,
  "replacement_event_inferred" BOOLEAN,
  "event_type_inferred" TEXT,
  "task_equipment_count" BIGINT,
  "association_confidence_score" BIGINT,
  "association_confidence_label" TEXT,
  "association_confidence_factors" TEXT,
  "after_hours_minutes" BIGINT,
  "business_minutes" BIGINT,
  "calculation_status" TEXT,
  "calculation_notes" TEXT
);

CREATE TABLE IF NOT EXISTS marts."equipment_part_lifecycle_intervals" (
  "equipment_internal_id" TEXT,
  "client_name" TEXT,
  "dolibarr_ref" TEXT,
  "dolibarr_label" TEXT,
  "previous_event_date" TIMESTAMPTZ,
  "current_event_date" TIMESTAMPTZ,
  "interval_days" BIGINT,
  "interval_months" DOUBLE PRECISION,
  "previous_fieldbeat_task_id" BIGINT,
  "current_fieldbeat_task_id" BIGINT,
  "event_count_for_machine_part" BIGINT,
  "association_confidence_score" BIGINT,
  "match_confidence" DOUBLE PRECISION,
  "interval_confidence_score" BIGINT,
  "interval_confidence_label" TEXT,
  "interval_confidence_factors" TEXT,
  "interval_status" TEXT
);

CREATE TABLE IF NOT EXISTS marts."fieldbeat_report_dolibarr_operational_view" (
  "fieldbeat_task_id" BIGINT,
  "fieldbeat_task_date" TIMESTAMPTZ,
  "client_key" TEXT,
  "client_rut" TEXT,
  "client_name" TEXT,
  "task_type" TEXT,
  "task_state" TEXT,
  "technician_names" TEXT,
  "equipment_internal_ids" TEXT,
  "linked_zendesk_ticket_id" TEXT,
  "zendesk_join_status" TEXT,
  "used_parts_count" BIGINT,
  "matched_used_parts_count" BIGINT,
  "placeholder_used_parts_count" BIGINT,
  "unmatched_used_parts_count" BIGINT,
  "ambiguous_used_parts_count" BIGINT,
  "review_required_used_parts_count" BIGINT,
  "dolibarr_refs" TEXT,
  "dolibarr_product_ids" TEXT,
  "used_part_numbers" TEXT,
  "used_part_names" TEXT,
  "part_match_statuses" TEXT,
  "part_match_methods" TEXT,
  "report_quality_status" TEXT
);

CREATE TABLE IF NOT EXISTS marts."fieldbeat_working_hours_analysis" (
  "fieldbeat_task_id" BIGINT,
  "client_key" TEXT,
  "client_rut" TEXT,
  "client_name" TEXT,
  "task_type" TEXT,
  "assigned_to" TEXT,
  "equipment_internal_ids" TEXT,
  "start_time_utc" TIMESTAMPTZ,
  "start_time_local" TIMESTAMP,
  "duration_minutes" BIGINT,
  "reported_start_raw" TEXT,
  "reported_end_raw" TEXT,
  "reported_interval_plausible" BOOLEAN,
  "estimated_end_time_local" TIMESTAMP,
  "business_minutes" BIGINT,
  "after_hours_weekday_minutes" BIGINT,
  "weekend_minutes" BIGINT,
  "holiday_minutes" BIGINT,
  "after_hours_total_minutes" BIGINT,
  "after_hours_rate" DOUBLE PRECISION,
  "is_after_hours_task" BOOLEAN,
  "calculation_method" TEXT,
  "calculation_status" TEXT,
  "calculation_notes" TEXT,
  "confidence_score" BIGINT,
  "confidence_label" TEXT,
  "confidence_color" TEXT,
  "confidence_factors" TEXT
);

CREATE TABLE IF NOT EXISTS marts."ticket_fieldbeat_dolibarr_operational_view" (
  "zendesk_ticket_id" BIGINT,
  "subject" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "has_fieldbeat_report" BOOLEAN,
  "fieldbeat_report_count" BIGINT,
  "has_multiple_fieldbeat_reports" BOOLEAN,
  "fieldbeat_task_ids" TEXT,
  "first_fieldbeat_start_time" TIMESTAMPTZ,
  "last_fieldbeat_start_time" TIMESTAMPTZ,
  "fieldbeat_states" TEXT,
  "fieldbeat_types" TEXT,
  "fieldbeat_assignees" TEXT,
  "client_names" TEXT,
  "equipment_internal_ids" TEXT,
  "has_used_parts" BOOLEAN,
  "used_parts_count" BIGINT,
  "used_part_numbers" TEXT,
  "operational_join_status" TEXT,
  "matched_used_parts_count" BIGINT,
  "placeholder_used_parts_count" BIGINT,
  "unmatched_used_parts_count" BIGINT,
  "ambiguous_used_parts_count" BIGINT,
  "manual_alias_match_count" BIGINT,
  "ref_exact_match_count" BIGINT,
  "ref_like_match_count" BIGINT,
  "review_required_used_parts_count" BIGINT,
  "dolibarr_product_ids" TEXT,
  "dolibarr_refs" TEXT,
  "used_part_names" TEXT,
  "part_match_methods" TEXT,
  "part_match_statuses" TEXT,
  "part_match_quality_status" TEXT,
  "data_quality_status" TEXT
);

CREATE TABLE IF NOT EXISTS marts."ticket_fieldbeat_operational_view" (
  "zendesk_ticket_id" BIGINT,
  "subject" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "has_fieldbeat_report" BOOLEAN,
  "fieldbeat_report_count" BIGINT,
  "has_multiple_fieldbeat_reports" BOOLEAN,
  "fieldbeat_task_ids" TEXT,
  "first_fieldbeat_start_time" TIMESTAMPTZ,
  "last_fieldbeat_start_time" TIMESTAMPTZ,
  "fieldbeat_states" TEXT,
  "fieldbeat_types" TEXT,
  "fieldbeat_assignees" TEXT,
  "client_names" TEXT,
  "equipment_internal_ids" TEXT,
  "has_used_parts" BOOLEAN,
  "used_parts_count" BIGINT,
  "used_part_numbers" TEXT,
  "operational_join_status" TEXT
);

CREATE TABLE IF NOT EXISTS marts."ticket_fieldbeat_report_detail" (
  "bridge_id" TEXT,
  "zendesk_ticket_id" BIGINT,
  "fieldbeat_task_id" BIGINT,
  "link_method" TEXT,
  "confidence" BIGINT,
  "task_type" TEXT,
  "state" TEXT,
  "priority" BIGINT,
  "description" TEXT,
  "client_name" TEXT,
  "assigned_to" TEXT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "start_time" TIMESTAMPTZ,
  "duration_minutes" BIGINT,
  "equipment_internal_ids" TEXT,
  "used_parts_count" BIGINT,
  "used_part_numbers" TEXT
);

CREATE TABLE IF NOT EXISTS marts."used_parts_dolibarr_match" (
  "used_part_id" TEXT,
  "fieldbeat_task_id" BIGINT,
  "zendesk_ticket_id" TEXT,
  "part_name" TEXT,
  "raw_part_identifier" TEXT,
  "normalized_part_identifier" TEXT,
  "dolibarr_product_id" BIGINT,
  "dolibarr_ref" TEXT,
  "dolibarr_barcode" TEXT,
  "dolibarr_label" TEXT,
  "match_method" TEXT,
  "match_confidence" DOUBLE PRECISION,
  "match_status" TEXT,
  "needs_manual_review" BOOLEAN,
  "candidate_dolibarr_product_ids" TEXT
);
